### PR TITLE
QVAC-17434 chore[bc]: migrate SDK plugins to new addon constructor shape

### PR DESCRIPTION
**Pull request by donriddo**
**Note**: be concise and prefer bullet points.

## 🎯 What problem does this PR solve?

- The embed, LLM, and diffusion addon interface refactors landed on `main`, but the matching SDK plugin migration did not.
- The built-in SDK plugins were still instantiating those addons with the old loader-based constructor shape, so the SDK branch was out of sync with the published addon APIs.
- The SDK also still carried old loader/model-path plumbing that no longer matched the addon contract.

## 📝 How does it solve it?

- Migrate the built-in `llamacpp-completion`, `llamacpp-embedding`, and `sdcpp-generation` plugins to the new single-argument addon constructor: `{ files, config, logger, opts }`.
- Return `{ model }` from migrated plugins and remove the old loader adapter path that is no longer used by those addons.
- Add `packages/sdk/server/utils/expand-gguf-shards.ts` so a single sharded GGUF path expands into the ordered `.tensors.txt` + shard list expected by the addon `files.model` contract.
- Remove obsolete SDK plumbing (`FilesystemDL`, `loader-adapter`, `model-path`) and bump the SDK's addon dependency versions to the refactored releases.
- Update unit coverage for shard expansion and adjust affected plugin tests to the new return shape.

## 🧪 How was it tested?

- On Linux, ran `bun run build` in `packages/sdk`.
- On Linux, ran `bun run test:unit` in `packages/sdk`.
- Added `expand-gguf-shards.test.ts` coverage for sharded and non-sharded paths, nested and relative paths, `1-of-1` shards, and Windows-style separators.
- Ran `bun install --frozen-lockfile` after the dependency bumps to confirm the lockfile resolves cleanly.

## 💥 Breaking Changes

- `PluginModelResult` no longer includes `loader`.
- Built-in SDK consumers are unaffected, but custom plugin authors returning `loader` must update to return only `model`.

**BEFORE:**

```typescript
export const myPlugin = definePlugin({
  // ...
  createModel(params: CreateModelParams): PluginModelResult {
    return { model, loader: null };
  },
});
```

**AFTER:**

```typescript
export const myPlugin = definePlugin({
  // ...
  createModel(params: CreateModelParams): PluginModelResult {
    return { model };
  },
});
```

### CODE REVIEW

**Comment by Proletter** [comment]
review

**Review by Proletter — DISMISSED** [review]

**Review by tamer-hassan-tether — DISMISSED** [review]

**Comment by Proletter** [comment]
review

**Review by tamer-hassan-tether — DISMISSED** [review]

**Review by ishanvohra2 — DISMISSED** [review]

File: packages/sdk/server/utils/expand-gguf-shards.ts [hunk 1]
```diff
@@ -0,0 +1,33 @@
...
+
+  const match = filename.match(SHARD_PATTERN);
+  if (!match || !match[1] || !match[3]) return [modelPath];
+
+  const baseFilename = match[1];
+  const totalShards = Number.parseInt(match[3], 10);
+  if (!Number.isFinite(totalShards) || totalShards <= 0) return [modelPath];
+
+  const join = (name: string) => (dir ? `${dir}${sep}${name}` : name);
+  const totalDigits = String(totalShards).padStart(5, "0");
```
Comment (yuranich) [inline packages/sdk/server/utils/expand-gguf-shards.ts]: Nit: `match[3]` is already the zero-padded 5-digit totals string captured by the regex — reconstructing it via `String(totalShards).padStart(5, "0")` does a redundant parse+format round trip. You can drop `totalDigits` and use `match[3]` directly in the loop.

File: packages/sdk/server/utils/expand-gguf-shards.ts [hunk 2]
```diff
@@ -0,0 +1,33 @@
...
+  const dir = lastSep >= 0 ? modelPath.slice(0, lastSep) : "";
+  const sep = lastSep >= 0 ? modelPath.charAt(lastSep) : "/";
+  const filename = lastSep >= 0 ? modelPath.slice(lastSep + 1) : modelPath;
+
+  const match = filename.match(SHARD_PATTERN);
+  if (!match || !match[1] || !match[3]) return [modelPath];
+
+  const baseFilename = match[1];
+  const totalShards = Number.parseInt(match[3], 10);
+  if (!Number.isFinite(totalShards) || totalShards <= 0) return [modelPath];
```
Comment (yuranich) [inline packages/sdk/server/utils/expand-gguf-shards.ts]: `parseInt`+`Number.isFinite` plus `<= 0` is belt-and-suspenders for a regex that already guarantees 5 digits — fine to keep as defensive, but worth a single-line test that `00000-of-00000.gguf` returns `[modelPath]` rather than an empty array so this branch is pinned down.

File: packages/sdk/server/utils/expand-gguf-shards.ts [hunk 3]
```diff
@@ -0,0 +1,33 @@
+const SHARD_PATTERN = /^(.+)-(\d{5})-of-(\d{5})\.gguf$/;
```
Comment (yuranich) [inline packages/sdk/server/utils/expand-gguf-shards.ts:1]: Consider extracting a pure `shard-patterns.ts` (regex + `generateShardFilenames`, no `bare-fs`) and importing it from both here and `shard-utils.ts`. Right now the shard regex and index-to-padded-filename logic is reimplemented with a slightly different contract (`.gguf`-only, case-sensitive) from `detectShardedModel()`'s extension-agnostic `(\.\w+)$` version. Two independent sources of truth for the same shard pattern is a latent footgun when shard naming evolves — worth a follow-up if not this PR.

**Comment by simon-iribarren** [comment]
Nice migration — the three refactored plugins look correct, the artifact-key renames for diffusion match `DiffusionFiles` in `@qvac/diffusion-cpp@0.3.0`, and `expand-gguf-shards.ts` has solid coverage (Windows, nested, `1-of-1`, substring regression).

One blocker before approval, though:

### Silent conflict with #1707 — merging as-is breaks the build

#1707 (`QVAC-17805` Bergamot companion-set grouping) merged into `main` earlier today and re-introduced `parseModelPath` usage in `packages/sdk/server/bare/plugins/nmtcpp-translation/plugin.ts`:

```ts
import { parseModelPath } from "@/server/utils";
...
function deriveColocatedBergamotVocabPaths(modelPath: string) {
  const { dirPath, basePath } = parseModelPath(modelPath);
  ...
}
```

This PR deletes `server/utils/model-path.ts` and drops `export * from "./model-path"` from `server/utils/index.ts`. The hunks don't textually overlap so GitHub still reports `MERGEABLE`, but post-merge `nmtcpp-translation/plugin.ts` imports a symbol that no longer exists → TS build failure. `bun run build --max-warnings=0` only passes on this branch because the PR base (`37d25181`) predates #1707.

Smallest fix: after rebasing, inline the two call sites with `bare-path` (already imported in that file):

```ts
const dirPath = path.dirname(modelPath);
const basePath = path.basename(modelPath);
```

That keeps the `model-path.ts` deletion intact.

### Scope / task linkage

The body reads exactly like QVAC-14392 ("Delete DataLoaders packages from SDK") — bumping addon deps, rewriting plugin constructors to the files-based API, deleting `loader-adapter` + `FilesystemDL` plumbing. Can you add `QVAC-14392` to the title or body so Asana auto-completes on merge? I'll pick up the follow-up that actually deletes `packages/qvac-lib-dl-{base,filesystem,hyperdrive}` from the monorepo once this lands.

### Bundled scope

The two `fix(examples)` commits for FLUX `guidance: 3.5, cfg_scale: 1` are unrelated to the interface migration (user-facing default change for example code). Happy to approve them inline, just flagging in case you'd rather ship them in their own PR for a cleaner changelog.

File: packages/sdk/server/utils/expand-gguf-shards.ts (hunk 1 above)
Comment (donriddo) [reply packages/sdk/server/utils/expand-gguf-shards.ts]: Done in [this commit](https://github.com/tetherto/qvac/pull/1688/commits/f9d8f3ae87f1e54515408748eabf859d16199314). Using `match[3]` directly now; it is already the zero-padded 5-digit string from the `(\d{5})` capture, so the `parseInt` + `padStart` round trip was pointless.

File: packages/sdk/server/utils/expand-gguf-shards.ts (hunk 2 above)
Comment (donriddo) [reply packages/sdk/server/utils/expand-gguf-shards.ts]: Done in [this commit](https://github.com/tetherto/qvac/pull/1688/commits/f9d8f3ae87f1e54515408748eabf859d16199314). Dropped `!Number.isFinite(totalShards)` since a `(\d{5})` match plus base-10 `parseInt` is always a finite integer. Kept the `<= 0` guard and added the `expandGGUFIntoShards: returns input for zero-total shard count` test to pin the `00000-of-00000.gguf` branch.

File: packages/sdk/server/utils/expand-gguf-shards.ts (hunk 3 above)
Comment (donriddo) [reply packages/sdk/server/utils/expand-gguf-shards.ts:1]: Leaving as a follow-up. The two helpers have intentionally different contracts: `shard-utils.ts:detectShardedModel` is extension-agnostic (`\.\w+`) because archive extraction consumes it for any shard format, whereas `expand-gguf-shards.ts` is GGUF-only since the `.tensors.txt` companion is a GGUF-specific artifact.

**Comment by donriddo** [comment]
> Nice migration — the three refactored plugins look correct, the artifact-key renames for diffusion match `DiffusionFiles` in `@qvac/diffusion-cpp@0.3.0`, and `expand-gguf-shards.ts` has solid coverage (Windows, nested, `1-of-1`, substring regression).
> 
> One blocker before approval, though:
> 
> ### Silent conflict with #1707 — merging as-is breaks the build
> #1707 (`QVAC-17805` Bergamot companion-set grouping) merged into `main` earlier today and re-introduced `parseModelPath` usage in `packages/sdk/server/bare/plugins/nmtcpp-translation/plugin.ts`:
> 
> ```ts
> import { parseModelPath } from "@/server/utils";
> ...
> function deriveColocatedBergamotVocabPaths(modelPath: string) {
>   const { dirPath, basePath } = parseModelPath(modelPath);
>   ...
> }
> ```
> 
> This PR deletes `server/utils/model-path.ts` and drops `export * from "./model-path"` from `server/utils/index.ts`. The hunks don't textually overlap so GitHub still reports `MERGEABLE`, but post-merge `nmtcpp-translation/plugin.ts` imports a symbol that no longer exists → TS build failure. `bun run build --max-warnings=0` only passes on this branch because the PR base (`37d25181`) predates #1707.
> 
> Smallest fix: after rebasing, inline the two call sites with `bare-path` (already imported in that file):
> 
> ```ts
> const dirPath = path.dirname(modelPath);
> const basePath = path.basename(modelPath);
> ```
> 
> That keeps the `model-path.ts` deletion intact.
> 
> ### Scope / task linkage
> The body reads exactly like QVAC-14392 ("Delete DataLoaders packages from SDK") — bumping addon deps, rewriting plugin constructors to the files-based API, deleting `loader-adapter` + `FilesystemDL` plumbing. Can you add `QVAC-14392` to the title or body so Asana auto-completes on merge? I'll pick up the follow-up that actually deletes `packages/qvac-lib-dl-{base,filesystem,hyperdrive}` from the monorepo once this lands.
> 
> ### Bundled scope
> The two `fix(examples)` commits for FLUX `guidance: 3.5, cfg_scale: 1` are unrelated to the interface migration (user-facing default change for example code). Happy to approve them inline, just flagging in case you'd rather ship them in their own PR for a cleaner changelog.

Thanks for the catch. Addressed in [this commit](https://github.com/tetherto/qvac/pull/1688/commits/f9d8f3ae87f1e54515408748eabf859d16199314) after rebasing onto current main:                                                                       
                                                   
  - `parseModelPath` usage in `nmtcpp-translation/plugin.ts:deriveColocatedBergamotVocabPaths` replaced with inline `path.dirname(modelPath)` + `path.basename(modelPath)` (`bare-path` is already imported). `server/utils/model-path.ts` stays        
  deleted.                                                                                                                                                                                                                                              
  - Updated the PR title.                                                                                                                                                                                                                 
  - Leaving the two FLUX example commits bundled here; it was intentional

**Review by simon-iribarren — DISMISSED** [review]

**Review by yuranich — DISMISSED** [review]

**Comment by simon-iribarren** [comment]
### Root cause of the SDK unit test failure

Looking at run [24882238163](https://github.com/tetherto/qvac/actions/runs/24882238163/job/72853352140), the failing step is **Run unit tests** with this crash (not a test assertion failure):

```
1 | module.exports = require.addon()
                             ^
TypeError: require.addon is not a function. (In 'require.addon()', 'require.addon' is undefined)
      at <anonymous> (.../node_modules/bare-type/binding.js:1:26)
      at <anonymous> (.../node_modules/bare-type/index.js:1:7)
      at <anonymous> (.../node_modules/bare-inspect/index.js:2:7)
      at <anonymous> (.../node_modules/bare-assert/index.js:1:7)
      at <anonymous> (.../node_modules/bare-crypto/lib/constants.js:1:9)

Bun v1.3.13 (Linux x64)
```

`require.addon()` is a Bare-only runtime API. Unit tests run under **Bun**, so any test file that transitively imports `bare-crypto` crashes while loading.

### Why this regressed now

It's caused by commit [`991686bb`](https://github.com/tetherto/qvac/pull/1688/commits/991686bb0296dada5d25d56627d300259945d5bd) ("route expand-gguf-shards import through server/utils barrel"):

- `packages/sdk/server/utils/index.ts` now re-exports `expand-gguf-shards`, alongside `./checksum` and `./formatting` — both of which do `import crypto from "bare-crypto"`.
- `packages/sdk/test/unit/expand-gguf-shards.test.ts` was changed from

  ```ts
  import { expandGGUFIntoShards } from "@/server/utils/expand-gguf-shards";
  ```

  to

  ```ts
  import { expandGGUFIntoShards } from "@/server/utils";
  ```

  Going through the barrel pulls in every sibling module, including `checksum.ts` and `formatting.ts`, which drags `bare-crypto` → `bare-assert` → `bare-inspect` → `bare-type` into the Bun process and blows up on `require.addon()`.

The earlier successful `check (sdk)` run on the prior PR head (`2dad6294`) did not have this issue because the test imported the module directly.

### Suggested fix

Revert the test's import to the direct file path:

```ts
import { expandGGUFIntoShards } from "@/server/utils/expand-gguf-shards";
```

The plugin imports (`llamacpp-completion/plugin.ts`, `llamacpp-embedding/plugin.ts`) going through the barrel are fine — those files only run under Bare, where `bare-crypto` works. It's specifically the unit test that cannot traverse the barrel.

As a broader cleanup (optional, separate PR), `server/utils/index.ts` shouldn't re-export Bare-coupled modules (`checksum`, `formatting`) if any non-Bare consumer might pull the barrel.

**Review by simon-iribarren — APPROVED** [review]

**Review by yuranich — APPROVED** [review]
